spring:
  application:
    name: graphServer
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.81:1521:orcl
    username: xingji
    password: xingji
    minIdle: 50
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    loginUsername: admin
    loginPassword: admin
    resetEnable: false
server:
  port: 8089
logging:
  file: graphServer.log
  path: logs
